### ISSUE TITLE
1장 깨끗한코드 오타

### ISSUE THREAD

**Issue by Odyflame** [kwj1270/TIL_CleanCode#4]
글 잘보고 있습니다.
1장에 마이클 페더스 쪽에 `몯느` 라고 오타가있네유 
이거 수정하면 좋을것같습니다~

**Comment by Odyflame** [comment]
+ 데이비스 토마스 부분의 마지막 글만 입니다~ 식으로 되어있어서 이것만 이다~ 느낌으로 바꿔도 좋을것같습니다

**Comment by kwj1270** [comment]
넵 알겠습니다 알려주셔서 감사합니다 :)
